(in-package #:llm-protocol-anthropic)

(defun %coerce-body-string (body)
  (cond
    ((stringp body) body)
    ((and (vectorp body) (not (stringp body)))
     (babel:octets-to-string body :encoding :utf-8))
    ((streamp body)
     (if (subtypep (stream-element-type body) 'character)
         (with-output-to-string (out)
           (loop for c = (read-char body nil nil)
                 while c
                 do (write-char c out)))
         (babel:octets-to-string
          (let ((out (make-array 0 :element-type '(unsigned-byte 8)
                                 :adjustable t :fill-pointer 0)))
            (loop for b = (read-byte body nil nil)
                  while b
                  do (vector-push-extend b out))
            out)
          :encoding :utf-8)))
    (t "")))

(defun %as-sse-source (body)
  (cond
    ((streamp body) body)
    ((stringp body) (make-string-input-stream body))
    ((and (vectorp body) (not (stringp body)))
     (make-string-input-stream (babel:octets-to-string body :encoding :utf-8)))
    (t (make-string-input-stream ""))))

(defun %map-sse (body function)
  (let ((src (%as-sse-source body)))
    (unwind-protect
         (sse-protocol:map-sse-events function src)
      (unless (eq src body)
        (ignore-errors (close src)))
      (when (streamp body)
        (ignore-errors (close body))))))

(defun %sse-json (event)
  (let ((data (and event (sse-protocol:sse-event-data event))))
    (when (stringp data)
      (let ((trimmed (string-trim '(#\Space #\Tab #\Newline #\Return) data)))
        (when (and (plusp (length trimmed))
                   (not (string-equal trimmed "[DONE]")))
          (ignore-errors (stack-json:decode trimmed)))))))

(defun %sse-event-type (event obj)
  (or (and event (sse-protocol:sse-event-type event))
      (and (hash-table-p obj) (gethash "type" obj))))

(defun %emit-part (on-part part)
  (when (and on-part part)
    (funcall on-part part)))

(defun %stream-body (backend path object)
  (multiple-value-bind (status body)
      (%request backend :post path object
                :want-stream t
                :accept "text/event-stream")
    (unless (<= 200 status 299)
      (%decode status (%coerce-body-string body)))
    body))

(defun %ensure-tool (table index)
  (or (gethash index table)
      (setf (gethash index table)
            (list :id nil :name nil :arguments "" :signature nil :thinking "" :text ""))))

(defun %consume-messages-sse (body on-part requested-model)
  (let ((text (make-string-output-stream))
        (thinking (make-string-output-stream))
        (signature nil)
        (tools (make-hash-table :test 'eql))
        (finish :stop)
        (usage nil)
        (seen-model nil)
        (id nil))
    (%map-sse
     body
     (lambda (event)
       (let ((obj (%sse-json event)))
         (when (hash-table-p obj)
           (let ((type (%sse-event-type event obj)))
             (cond
               ((string-equal type "message_start")
                (let ((msg (gethash "message" obj)))
                  (when (hash-table-p msg)
                    (setf id (gethash "id" msg)
                          seen-model (or (gethash "model" msg) seen-model)
                          usage (or (%usage (gethash "usage" msg)) usage)))))
               ((string-equal type "content_block_start")
                (let* ((idx (or (gethash "index" obj) 0))
                       (block (gethash "content_block" obj)))
                  (when (hash-table-p block)
                    (let ((btype (gethash "type" block)))
                      (when (string-equal btype "tool_use")
                        (let ((acc (%ensure-tool tools idx)))
                          (setf (getf acc :id) (gethash "id" block)
                                (getf acc :name) (gethash "name" block))
                          (setf (gethash idx tools) acc)))))))
               ((string-equal type "content_block_delta")
                (let* ((idx (or (gethash "index" obj) 0))
                       (delta (gethash "delta" obj)))
                  (when (hash-table-p delta)
                    (let ((dtype (gethash "type" delta)))
                      (cond
                        ((string-equal dtype "text_delta")
                         (let ((tx (%str (gethash "text" delta))))
                           (when (plusp (length tx))
                             (write-string tx text)
                             (%emit-part on-part (make-llm-text-part :text tx)))))
                        ((string-equal dtype "thinking_delta")
                         (let ((tx (%str (gethash "thinking" delta))))
                           (when (plusp (length tx))
                             (write-string tx thinking)
                             (%emit-part on-part
                                         (make-llm-thinking-part :text tx)))))
                        ((string-equal dtype "signature_delta")
                         (setf signature (%str (gethash "signature" delta))))
                        ((string-equal dtype "input_json_delta")
                         (let ((acc (%ensure-tool tools idx))
                               (partial (%str (gethash "partial_json" delta))))
                           (setf (getf acc :arguments)
                                 (concatenate 'string (getf acc :arguments)
                                              partial))
                           (setf (gethash idx tools) acc))))))))
               ((string-equal type "message_delta")
                (let ((delta (gethash "delta" obj)))
                  (when (hash-table-p delta)
                    (when (gethash "stop_reason" delta)
                      (setf finish (%finish-reason (gethash "stop_reason" delta)))))
                  (when (gethash "usage" obj)
                    (setf usage (%usage (gethash "usage" obj))))))
               ((string-equal type "error")
                (error 'llm-http-error
                       :retryable-p nil
                       :message (%error-message obj "stream error")))))))))
    (let* ((think-s (get-output-stream-string thinking))
           (text-s (get-output-stream-string text))
           (calls (mapcar (lambda (k)
                            (let ((acc (gethash k tools)))
                              (make-llm-tool-call-part
                               :id (getf acc :id)
                               :name (or (getf acc :name) "")
                               :arguments (or (getf acc :arguments) ""))))
                          (sort (loop for k being the hash-keys of tools collect k)
                                #'<))))
      (dolist (call calls)
        (%emit-part on-part call))
      (make-llm-response
       :id id
       :parts (append (and (plusp (length think-s))
                           (list (make-llm-thinking-part :text think-s
                                                         :signature signature)))
                      (and (plusp (length text-s))
                           (list (make-llm-text-part :text text-s)))
                      calls)
       :model (or seen-model requested-model)
       :finish-reason (if calls :tool-use (or finish :stop))
       :usage usage))))

(defmethod stream-generate ((backend anthropic-backend) turns &key model settings
                            tools tool-choice on-part output)
  (declare (ignore output))
  (multiple-value-bind (model body)
      (%messages-body backend turns :model model :settings settings
                      :tools tools :tool-choice tool-choice :stream t)
    (%consume-messages-sse (%stream-body backend "/messages" body)
                           on-part model)))
